language: python

python:
  - "3.5"

install:
  - pip install codecov coverage httmock requests odfpy psycopg2

script:
  - python3 test_gatherer.py
  - python3 test_diff_computer.py
  - COVERAGE_FILE=.coverage_gth coverage run test_gatherer.py
  - COVERAGE_FILE=.coverage_diff coverage run test_diff_computer.py
  - coverage combine .coverage_gth .coverage_diff

after_success:
  - codecov

notifications:
  email: false

  slack:
    rooms:
      - owllit:GRN6KTTcUiujsRDPbBROMEr0
    on_success: never
    on_failure: always
