language: python

python:
  - "3.5"

services:
  - postgresql

install:
  - pip install codecov coverage httmock requests odfpy psycopg2

before_script:
  - psql -c "CREATE DATABASE test_storage;" -U postgres

script:
  - coverage run run_tests.py

after_success:
  - codecov

notifications:
  email: false
